In [3]:
pip install numpy

In [4]:
(numpy._version_)


NameError: name 'numpy' is not defined

In [ ]:
import numpy as np
np.__version__


In [ ]:
------------------------arrays-------------------------

In [ ]:
0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.
An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.
An array that has 1-D arrays as its elements is called a 2-D array.
An array that has 2-D arrays (matrices) as its elements is called 3-D array.

In [ ]:
-------------------------0D array---------------------------

In [ ]:
a=np.array(65) #0 dimensional array
a.ndim   #returns dimensions

In [ ]:
------------------------1D array----------------------------

In [13]:
b=np.array([1,2,3,4])
b

array([1, 2, 3, 4])

In [11]:

b=np.array([1,2,3,4])
print(b[1] )  #accessing an array

2


In [22]:
b.ndim

1

In [12]:
b.shape #returns no of rows and columns

(4,)

In [ ]:
------------------------2D array--------------------------

In [15]:
c=np.array([[1,2,4],[3,5,6]])
c.shape #returns rows and columns

(2, 3)

In [14]:
c[0,2:4] #slicing   2 is included 4 is excluded

NameError: name 'c' is not defined

In [6]:
c[0:2,2] #returns 3rd element of both rows

array([4, 6])

In [23]:
c[1,2]  #[row,col] accesing

6

In [ ]:
---------------------------3D array-----------------------------

In [17]:
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [42, 57, 6]]])
d.ndim
d.shape

(2, 2, 3)

In [24]:
d[0,0,1] #first number represents 1st dimension ie.  [[1,2,3],[4,5,6]]
         #second number represents 1st dimension in the array [[1,2,3],[4,5,6]] ie.[1,2,3]
        #last number represents 2nd element ie. 2

2

In [18]:
d[0:2,1,0:2]

array([[ 4,  5],
       [42, 57]])

In [27]:
d.itemsize  #returns size of an particular element

4

In [ ]:
# d.nbytes  #returns total size of array

In [31]:
d.dtype #returns type of item

dtype('int32')

In [18]:
arr = np.array([1, 2, 3, 4], ndmin=5)  #creating an array of dimension 5 using ndmin
arr.ndim

5

In [19]:
arr.shape

(1, 1, 1, 1, 4)

In [ ]:
-----------------zeros ones identity of array-----------------------

In [34]:
s=np.zeros((2,3))
s

array([[0., 0., 0.],
       [0., 0., 0.]])

In [35]:
s=np.ones((4,1))
s

array([[1.],
       [1.],
       [1.],
       [1.]])

In [36]:
r=np.ones((2,3,4))
r

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [7]:
k=np.full((2,3),99)
k

array([[99, 99, 99],
       [99, 99, 99]])

In [11]:
f=np.random.rand(4,2) #will change for every run
f

array([[0.34745448, 0.80684144],
       [0.7828018 , 0.6447462 ],
       [0.27910375, 0.39988945],
       [0.23982778, 0.15545262]])

In [12]:
c=np.identity(5)
c

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
---------------coping an array---------------

In [8]:
a=np.array([1,2,3,4])
b=a
b[0]=12        #this will change in a also
a         

array([12,  2,  3,  4])

In [10]:
a=np.array([1,2,3,4])
b=a.copy()
b[0]=12        #this wont change in a as we used copy()
a  

array([1, 2, 3, 4])

In [16]:
n= np.array([1, 2, 3, 4, 5])
x = n.view()
n[0] = 42       #changes in x reflect in n

In [ ]:
d.ndim #returns the dimensions of array
d.shape  #returns the no of rows and columns
d.itemsize  #returns size of an particular element
d.nbytes  #returns total size of array
d.dtype #returns type of item
arr = np.array([1, 2, 3, 4], ndmin=5)  #creating an array of dimension 5 using ndmin

0D array
a=np.array(65)

1D array
b=np.array([1,2,3,4])
c[1]

2D array
c=np.array([[1,2,4],[3,5,6]])
c[1,2]  #[row,col] accesing of 2D array
c[0,2:4] #slicing   2 is included 4 is excluded
c[0:2,2] #returns 3rd element of both rows

3D array
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [42, 57, 6]]])
d[0,0,1] #first number represents 1st dimension ie.  [[1,2,3],[4,5,6]]
         #second number represents 1st dimension in the array [[1,2,3],[4,5,6]] ie.[1,2,3]
        #last number represents 2nd element ie. 2
d[0:2,1,0:2]


s=np.zeros((2,3)) #creates 2 rows 3 columns with 0
r=np.ones((2,3,4))
k=np.full((2,3),99) #creates 2 rows 3 columns with 99
f=np.random.rand(4,2) #will change for every run
c=np.identity(5)      #return identity matrix with size 5

b=a.copy()  #changes in b wont effect a 
x = n.view() #changes in x reflect in n